### ISSUE TITLE
Training and inference examples

### ISSUE THREAD

**Issue by WarranWeng** [XiYe20/NPVP#1]
Hi, thanks for the great work. Could you please provide some examples about the training and inference if possible? Such as dataset, pretrained model and inference code?

**Comment by NPVS** [comment]
Hi, Thank you very much for your interest in our work. We have updated the documentation and inference examples.

**Comment by XiYe20** [comment]
Hi, Thank you so much for your interest in our work. We have updated the documentation and inference examples.
